name: Push to Powershell Gallery

on:
  release:
    types: [published]

jobs:
  push:
    runs-on: windows-latest

    steps:
    - name: Get Sources
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore GetBoolChoice.sln
      
    - name: Build
      run: dotnet build GetBoolChoice.sln --no-restore --output ./out
      
    - name: Get files in OUTPUT directory
      run: |
        ls ./out
      shell: pwsh
      
    - name: Test PowerShell Module Manifest
      run: |
        Test-ModuleManifest -Path ./out/GetBoolChoice.psd1
      shell: pwsh
      
    - name: Publish PowerShell Module
      run: |
        Publish-Module -Path ./out -Repository PSGallery -NuGetApiKey ${{secrets.POWERSHELLMODULES_API_KEY}}
      shell: pwsh
